# Generated by Django 3.2.4 on 2021-06-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name': 'Directory', 'verbose_name_plural': 'Directorys'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
    ]
